# final_alice/yandex_sites/Dockerfile
FROM python:3.11

WORKDIR /app

COPY ./.env .
COPY ./yandex_sites/ .


RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python", "site.py"]
