"""Initiall

Revision ID: 391d731aed81
Revises: 
Create Date: 2024-10-28 23:59:13.707730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '391d731aed81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time1', sa.String(), nullable=False),
    sa.Column('site1', sa.String(), nullable=False),
    sa.Column('time2', sa.String(), nullable=False),
    sa.Column('site2', sa.String(), nullable=False),
    sa.Column('time3', sa.String(), nullable=False),
    sa.Column('site3', sa.String(), nullable=False),
    sa.Column('time4', sa.String(), nullable=False),
    sa.Column('site4', sa.String(), nullable=False),
    sa.Column('time5', sa.String(), nullable=False),
    sa.Column('site5', sa.String(), nullable=False),
    sa.Column('time6', sa.String(), nullable=False),
    sa.Column('site6', sa.String(), nullable=False),
    sa.Column('time7', sa.String(), nullable=False),
    sa.Column('site7', sa.String(), nullable=False),
    sa.Column('time8', sa.String(), nullable=False),
    sa.Column('site8', sa.String(), nullable=False),
    sa.Column('time9', sa.String(), nullable=False),
    sa.Column('site9', sa.String(), nullable=False),
    sa.Column('time10', sa.String(), nullable=False),
    sa.Column('site10', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('role', cascade=True)
    op.drop_table('user')
    op.drop_constraint('user_role_id_fkey', 'user', type_='foreignkey')
    op.drop_table('role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('registered_t', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='user_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='role_pkey')
    )
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
