"""Описание изменений

Revision ID: 78b47112d8e4
Revises: dd6872df447f
Create Date: 2024-12-26 03:27:59.991905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b47112d8e4'
down_revision: Union[str, None] = 'dd6872df447f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('payment_auto', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('payment_method_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'payment_method_id')
    op.drop_column('user', 'payment_auto')
    # ### end Alembic commands ###
